environment:
  cookie_root_domain: .o6s.io
  external_domain: https://Qolzam.o6s.io
  external_redirect_domain: https://Qolzam.o6s.io/auth
  gateway: https://Qolzam.o6s.io
  origin: https://Qolzam.o6s.io
  web_domain: https://Qolzam.o6s.io
  websocket_server_url: https://red-gold-socket.herokuapp.com
